name: SneakersShopCI
values:
  - key: baseUrl
    value: 'https://localhost:7149'
    enabled: true
  - key: accessToken
    value: ''
    enabled: true
  - key: refreshToken
    value: ''
    enabled: true
